package agenttest

import (
	"context"
	"encoding/json"
	"fmt"
	"slices"
	"sort"
	"strings"

	"github.com/urmzd/saige/agent/types"
)

// EmulatorConfig configures NewToolCallEmulator.
type EmulatorConfig struct {
	// Tools restricts which offered tools are called, in this order. Empty
	// calls every offered tool, in the order the request lists them.
	Tools []string
	// Rounds is how many tool-calling turns run before the answer. Zero
	// means one.
	Rounds int
	// RequiredOnly fills only required properties. By default every
	// declared property gets a value, so optional parameters are exercised
	// too.
	RequiredOnly bool
	// Answer is the final text. Empty answers with one "name: result" line
	// per tool result of the last round. A call with a response schema
	// answers with FakeValue's JSON for the schema instead.
	Answer string
	// Usage, when set, is reported on every turn.
	Usage *types.UsageDelta
}

// NewToolCallEmulator returns a model that calls tools without an LLM: on
// each tool-calling turn it calls the offered tools with schema-valid
// arguments generated by FakeArguments, and once the configured rounds have
// run it answers. The output depends only on the request, so a test of tool
// plumbing (registration, schemas, gates, markers, result handling) is
// deterministic.
//
// It honors the request's tool choice: none answers at once, and a named
// choice calls only that tool. The returned FunctionModel's fields, such as
// Caps or CatalogModel, can be set before use.
func NewToolCallEmulator(cfg EmulatorConfig) *FunctionModel {
	rounds := cfg.Rounds
	if rounds <= 0 {
		rounds = 1
	}
	return &FunctionModel{
		ProviderName: "emulator",
		ModelName:    "tool-call-emulator",
		Fn: func(_ context.Context, messages []types.Message, tools []types.ToolDef, req Request) (Response, error) {
			resp := Response{Usage: cfg.Usage}
			calls := selectTools(cfg.Tools, tools, req.Effective.ToolChoice)
			if len(calls) > 0 && toolRounds(messages) < rounds {
				for _, def := range calls {
					resp.ToolCalls = append(resp.ToolCalls, types.ToolUseContent{
						Name:      def.Name,
						Arguments: FakeArguments(def.Parameters, !cfg.RequiredOnly),
					})
				}
				resp.FinishReason = "tool_use"
				return resp, nil
			}
			resp.FinishReason = "stop"
			switch {
			case req.Schema != nil:
				raw, err := json.Marshal(FakeValue(*req.Schema, !cfg.RequiredOnly))
				if err != nil {
					return Response{}, err
				}
				resp.Text = string(raw)
			case cfg.Answer != "":
				resp.Text = cfg.Answer
			default:
				resp.Text = summarizeResults(messages)
			}
			return resp, nil
		},
	}
}

// selectTools returns the tools one turn calls.
func selectTools(want []string, offered []types.ToolDef, choice *types.ToolChoice) []types.ToolDef {
	if choice != nil && choice.Mode == types.ToolChoiceNone {
		return nil
	}
	var out []types.ToolDef
	if len(want) == 0 {
		out = offered
	} else {
		for _, name := range want {
			if i := slices.IndexFunc(offered, func(d types.ToolDef) bool { return d.Name == name }); i >= 0 {
				out = append(out, offered[i])
			}
		}
	}
	if choice != nil && choice.Mode == types.ToolChoiceNamed {
		i := slices.IndexFunc(offered, func(d types.ToolDef) bool { return d.Name == choice.Name })
		if i < 0 {
			return nil
		}
		return []types.ToolDef{offered[i]}
	}
	return out
}

// toolRounds counts the assistant turns with tool calls since the last
// user text.
func toolRounds(messages []types.Message) int {
	n := 0
	for i := len(messages) - 1; i >= 0; i-- {
		switch m := messages[i].(type) {
		case types.UserMessage:
			if slices.ContainsFunc(m.Content, func(c types.UserContent) bool { _, ok := c.(types.TextContent); return ok }) {
				return n
			}
		case types.AssistantMessage:
			if slices.ContainsFunc(m.Content, func(c types.AssistantContent) bool { _, ok := c.(types.ToolUseContent); return ok }) {
				n++
			}
		}
	}
	return n
}

// summarizeResults renders the results of the last tool round as one
// "name: result" line each.
func summarizeResults(messages []types.Message) string {
	names := map[string]string{}
	last := -1
	for i, m := range messages {
		if am, ok := m.(types.AssistantMessage); ok {
			for _, c := range am.Content {
				if tu, ok := c.(types.ToolUseContent); ok {
					names[tu.ID] = tu.Name
					last = i
				}
			}
		}
	}
	var lines []string
	add := func(c any) {
		if r, ok := c.(types.ToolResultContent); ok {
			text := r.Text
			if r.IsError {
				text = "error: " + text
			}
			lines = append(lines, names[r.ToolCallID]+": "+text)
		}
	}
	for _, m := range messages[last+1:] {
		switch v := m.(type) {
		case types.SystemMessage:
			for _, c := range v.Content {
				add(c)
			}
		case types.UserMessage:
			for _, c := range v.Content {
				add(c)
			}
		}
	}
	if last < 0 || len(lines) == 0 {
		return "no tool results"
	}
	return strings.Join(lines, "\n")
}

// FakeArguments returns arguments that satisfy schema, derived only from
// the schema so the same schema always yields the same arguments. Every
// required property is set; optional ones are set too when all is true.
// Values come from, in order: a property's default, its first enum value,
// and a fixed sample for its type (a string named after the property, 1,
// 1.5, true, a one-element array, or a nested object).
func FakeArguments(schema types.ParameterSchema, all bool) map[string]any {
	return fakeObject(schema.Properties, schema.Required, all)
}

// FakeValue returns a schema-valid JSON value for a whole schema: an object
// for an object schema, as FakeArguments builds it.
func FakeValue(schema types.ParameterSchema, all bool) any {
	if schema.Type != "" && schema.Type != types.SchemaObject {
		return fakeProperty("value", types.PropertyDef{Type: schema.Type}, all)
	}
	return FakeArguments(schema, all)
}

func fakeObject(props map[string]types.PropertyDef, required []string, all bool) map[string]any {
	out := map[string]any{}
	names := make([]string, 0, len(props))
	for name := range props {
		if all || slices.Contains(required, name) {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		out[name] = fakeProperty(name, props[name], all)
	}
	// A required property the schema does not describe still has to be
	// present.
	for _, name := range required {
		if _, ok := out[name]; !ok {
			out[name] = name
		}
	}
	return out
}

func fakeProperty(name string, p types.PropertyDef, all bool) any {
	if p.Default != nil {
		return p.Default
	}
	if len(p.Enum) > 0 {
		return enumValue(p.Type, p.Enum[0])
	}
	switch p.Type {
	case types.SchemaInteger:
		return 1
	case types.SchemaNumber:
		return 1.5
	case types.SchemaBoolean:
		return true
	case types.SchemaArray:
		if p.Items == nil {
			return []any{}
		}
		return []any{fakeProperty(name, *p.Items, all)}
	case types.SchemaObject:
		return fakeObject(p.Properties, p.Required, all)
	}
	return fmt.Sprintf("sample %s", name)
}

// enumValue converts an enum entry, which ParameterSchema stores as a
// string, to the property's type.
func enumValue(typ, v string) any {
	var out any
	switch typ {
	case types.SchemaInteger, types.SchemaNumber, types.SchemaBoolean:
		if json.Unmarshal([]byte(v), &out) == nil {
			return out
		}
	}
	return v
}
