run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - goconst
        - gocyclo
    - path: examples/
      linters:
        - gosec
        - errcheck
